"""Generates GENESIS control files from a typed config via Jinja2
templates, and supports round-tripping user edits.

See resources/templates/_common_sections.j2 and the per-model templates
for short per-keyword citations; see DECISIONS.md for the full writeup
of what's confirmed against which mdgenesis.org tutorial or a real
installed GENESIS's `-h ctrl_all` output.
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from jinja2 import Environment, FileSystemLoader, select_autoescape

from app.project import ModelType
from app.text_io import write_generated_text

TEMPLATES_DIR = Path(__file__).resolve().parent.parent / "resources" / "templates"

_TEMPLATE_BY_MODEL = {
    ModelType.AICG2P: "aicg2p.j2",
    ModelType.HPS_SINGLE: "hps_single.j2",
    ModelType.HPS_CONDENSATE: "hps_condensate.j2",
    ModelType.PROTEIN_DNA: "protein_dna.j2",
    ModelType.ALL_ATOM_CHARMM: "all_atom_charmm.j2",
}


@dataclass
class ControlFileConfig:
    top_file: str
    gro_file: str
    output_prefix: str
    temperature_k: float
    n_steps: int
    timestep_fs: float
    output_frequency: int
    langevin_friction: float
    ensemble: str = "NVT"
    pressure_atm: float = 1.0  # GENESIS User Guide 2.0.0 Sec. 10.1 default target pressure, only used when ensemble == "NPT"
    use_position_restraints: bool = False
    position_restraint_force_constant: float = 10.0  # GENESIS User Guide 2.0.0 Sec. 16.4's own POSI example
    remd_enabled: bool = False
    remd_exchange_period: int = 1000
    remd_temperatures: Optional[list] = None
    gamd_enabled: bool = False
    gamd_update_period: int = 0
    gamd_sigma0_pot: float = 6.0
    restart_file: Optional[str] = None
    box_x: Optional[float] = None
    box_y: Optional[float] = None
    box_z: Optional[float] = None
    engine: str = "atdyn"
    # -- ALL_ATOM_CHARMM only (Roadmap Phase 5): a pre-built system's own files, not
    # generated by this app -- see ModelType.ALL_ATOM_CHARMM and all_atom_charmm.j2.
    aa_top_files: Optional[list] = None  # CHARMM topfile(s), e.g. ["top_all36_prot.rtf"]
    aa_par_files: Optional[list] = None  # CHARMM parfile(s), e.g. ["par_all36m_prot.prm"]
    aa_str_files: Optional[list] = None  # optional CHARMM stream file(s), e.g. toppar_water_ions.str
    aa_psf_file: Optional[str] = None
    aa_pdb_file: Optional[str] = None
    minimize_method: str = "SD"  # genesis_tutorial_materials tutorial-3.3 2_minimize/INP (PDB 2QMT)
    minimize_nsteps: int = 2000  # tutorial-3.3 2_minimize/INP
    # Which binary (app.project.Engine.value) will actually run this
    # control file. Matters because at least one keyword's valid values
    # differ by engine: confirmed 2026-09-10 against real installed
    # GENESIS 2.1.6 `-h ctrl_all` output that `cgdyn` only accepts
    # integrator [LEAP,VVER] while `atdyn` additionally accepts
    # VVER_CG -- see _common_sections.j2 and DECISIONS.md.


def _environment() -> Environment:
    # Control files are plain text (INI-style), not HTML/XML, so autoescape
    # is intentionally off.
    return Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=select_autoescape(disabled_extensions=(".j2",), default=False),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
    )


MODEL_TYPES_REQUIRING_BOX = (ModelType.HPS_CONDENSATE, ModelType.AICG2P, ModelType.ALL_ATOM_CHARMM)
# ALL_ATOM_CHARMM requires a box because Phase 5 only implements the standard
# explicit-solvent PME case (GENESIS User Guide 2.0.0 Sec. 6.2: "PME... only
# availabe in the periodic boundary condition"); implicit-solvent/NOBC all-atom
# (GBSA/EEF1) is documented but not implemented -- see DECISIONS.md.
# AICG2P needs box_x/y/z too because mdgenesis.org tutorial 11.1's own
# single-protein (1PGB) example runs under [BOUNDARY] type = PBC with an
# explicit box, not NOBC as previously assumed — see aicg2p.j2 and
# DECISIONS.md.


# mdgenesis.org tutorial 11.1's own example system (1PGB, 56 residues)
# uses a 180.0 x 180.0 x 180.0 box; used as the fallback whenever a
# project has no explicit SimulationParameters.box_size_nm set, for
# whichever model type needs one (see MODEL_TYPES_REQUIRING_BOX).
DEFAULT_BOX_SIZE = 180.0
# tutorial 11.4's FUS condensate example (fus_120.inp) uses this exact
# slab box -- corrected 2026-09-11 from an earlier unverified (20,20,200)
# guess made before any condensate tutorial had been found.
DEFAULT_CONDENSATE_BOX = (180.0, 180.0, 1800.0)


def default_box_size(model_type: ModelType, box_size: Optional[float]) -> tuple:
    """Resolve (box_x, box_y, box_z) for a project, applying the same
    tutorial-derived fallback used by every ControlFileConfig call site so
    a project without an explicit box size still renders instead of
    raising. Returns (None, None, None) for model types that don't need a
    box at all."""
    if model_type == ModelType.HPS_CONDENSATE:
        if box_size is not None:
            return (box_size, box_size, box_size)
        return DEFAULT_CONDENSATE_BOX
    if model_type == ModelType.AICG2P:
        size = box_size if box_size is not None else DEFAULT_BOX_SIZE
        return (size, size, size)
    return (None, None, None)


def render_control_file(config: ControlFileConfig, model_type: ModelType) -> str:
    template_name = _TEMPLATE_BY_MODEL[model_type]
    if model_type in MODEL_TYPES_REQUIRING_BOX and (
        config.box_x is None or config.box_y is None or config.box_z is None
    ):
        raise ValueError(f"{model_type.value} control files require box_x/box_y/box_z")
    if config.ensemble != "NVT" and model_type not in MODEL_TYPES_REQUIRING_BOX:
        # NPT/NPAT/NPgT couple to the periodic box; NOBC model types (HPS_SINGLE,
        # PROTEIN_DNA) have no box for a barostat to act on.
        raise ValueError(f"{model_type.value} has no periodic box; only NVT is valid for it")
    if config.remd_enabled and len(config.remd_temperatures or []) < 2:
        # GENESIS User Guide 2.0.0 Ch. 15: T-REMD needs at least 2 replicas to exchange between.
        raise ValueError("REMD needs at least 2 replica temperatures")
    if config.gamd_enabled and config.gamd_update_period <= 0:
        # Sec. 17.1: update_period == 0 means GaMD parameters are never updated -- a
        # syntactically valid but scientifically inert control file, not a real GaMD run.
        raise ValueError("GaMD needs update_period > 0 to actually adapt its boost potential")
    if model_type == ModelType.ALL_ATOM_CHARMM and not (
        config.aa_top_files and config.aa_par_files and config.aa_psf_file and config.aa_pdb_file
    ):
        # GENESIS User Guide 2.0.0 Sec. 4.1.1: CHARMM needs topfile+parfile+psffile+pdbfile,
        # all prepared by an external setup tool (VMD/PSFGEN, CHARMM-GUI, or CHARMM) -- this
        # app cannot fabricate a default for files it never generated.
        raise ValueError("all_atom_charmm requires aa_top_files, aa_par_files, aa_psf_file, and aa_pdb_file")
    env = _environment()
    template = env.get_template(template_name)
    return template.render(config=config)


def write_control_file(
    config: ControlFileConfig,
    model_type: ModelType,
    local_directory: str,
    filename: str = "run.inp",
    force: bool = False,
) -> Path:
    """Write the rendered control file into `local_directory/filename`.

    If a file already exists at that path and `force` is False, it is left
    untouched and its path is returned unchanged — this is the "keep my
    edits" side of the Files tab's regenerate-vs-keep-edits choice; callers
    that want to overwrite (the "Regenerate" action) must pass force=True.
    """
    path = Path(local_directory) / filename
    if path.exists() and not force:
        return path
    path.parent.mkdir(parents=True, exist_ok=True)
    write_generated_text(path, render_control_file(config, model_type))
    return path


def render_minimize_control_file(config: ControlFileConfig) -> str:
    """All-atom-only (Roadmap Phase 5 follow-up): a short energy-minimization
    control file, run automatically before the main MD run for every
    ALL_ATOM_CHARMM project (app/project_creation.py's run_minimization()) --
    confirmed against genesis_tutorial_materials tutorial-3.3/2_minimize/INP.
    Not offered for CG model types: their own tutorials go straight to MD
    with no separate minimization stage.
    """
    if not (config.aa_top_files and config.aa_par_files and config.aa_psf_file and config.aa_pdb_file):
        raise ValueError("minimize control file requires aa_top_files, aa_par_files, aa_psf_file, and aa_pdb_file")
    if config.box_x is None or config.box_y is None or config.box_z is None:
        raise ValueError("minimize control file requires box_x/box_y/box_z")
    env = _environment()
    template = env.get_template("all_atom_minimize.j2")
    return template.render(config=config)


def write_minimize_control_file(
    config: ControlFileConfig, local_directory: str, filename: str = "minimize.inp", force: bool = False
) -> Path:
    path = Path(local_directory) / filename
    if path.exists() and not force:
        return path
    path.parent.mkdir(parents=True, exist_ok=True)
    write_generated_text(path, render_minimize_control_file(config))
    return path
